version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  ffmpeg-hls:
    image: jrottenberg/ffmpeg:latest
    container_name: ffmpeg-hls
    entrypoint: >
      bash -c "ffmpeg -rtsp_transport tcp -i ${RTSP_URL}
      -c:v copy -c:a aac -f hls -hls_time 2 -hls_list_size 3 -hls_flags delete_segments /output/stream.m3u8"
    volumes:
      - ./stream:/output
    restart: always

  frontend:
    build: ./frontend
    volumes:
      - ./stream:/app/public/stream
    depends_on:
      - backend
      - ffmpeg-hls

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: